<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-25 16:19
=======
# Generated by Django 6.0.2 on 2026-02-23 14:26
>>>>>>> user-places-sos-dairy

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Tourist Places', 'Tourist Places'), ('Hospitals', 'Hospitals'), ('Police Stations', 'Police Stations'), ('Restaurants', 'Restaurants')], max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
            ],
        ),
    ]
