# Generated by Django 6.0.2 on 2026-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_touristplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='category',
            field=models.CharField(choices=[('Tourist Places', 'Tourist Places'), ('Hospitals', 'Hospitals'), ('Police Stations', 'Police Stations'), ('Restaurants', 'Restaurants')], max_length=50),
        ),
    ]
