# Generated by Django 4.2.7 on 2026-02-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_touristplace_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TouristPlace',
        ),
    ]
