# Generated by Django 6.0.2 on 2026-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='email',
            field=models.EmailField(default='nandanathuyath@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
